version: '3.4'
services:

  front:
    build:
      context: .
      dockerfile: ./front/Dockerfile
      network: host
    restart: always
    container_name: front
    depends_on:
      - back
    ports:
      - 8888:8888
    networks:
      - network

  back:
    build:
      context: .
      dockerfile: ./back/Dockerfile
      network: host
    restart: always
    container_name: back
    ports:
      - 9999:9999
    networks:
      - network

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.103.0.0/16


